spring:
  logging:
    group:
      db: 'org.hibernate,org.springframework.data.jpa,org.springframework.jdbc'
    level:
      db: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:25432/webapp
    username: db-dev-user
    password: db-dev-pass
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      pool-name: 'hikari-pool'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        tmp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: none
    open-in-view: false
    show-sql: true

  # Java Mail config
  mail:
    host: localhost
    username: <login user to smtp server>
    password: <login password to smtp server>
    port: '1025'
    properties:
      mail:
        smtp:
          auth: 'false'
          starttls:
            enable: 'false'
            required: 'false'
          # Enable, if target server expects SSL instead of STARTTLS
          #socketFactory:
          #  port: '1025'
          #  class: javax.net.ssl.SSLSocketFactor
          #  fallback: 'false'

business:
  adminUsers:
    - admin.user@denktmit.de
  domainNames:
    - denktmit.de
  mail:
    sender: "mailbot@denktmit.de"